inputs:
  port:
    description: 'Port for node app to run'
    default: 1010
  environment:
    description: 'Env for node app'
    default: 'DEV'

runs:
  using: "composite"
  steps:
    - name: ... build success ...
      run: echo Start to deploy to dev ..
      shell: bash
    - name: install dependencies
      run: npm install
      shell: bash