name: sample-book-app

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

      # - name: ... build success ...
      #   run: echo build success! ..
      
      # - name: ... check node version ...
      #   run: node -v

      # - name: ... check node and npm version ...
      #   run: | 
      #     node -v
      #     node -v
      #     pm2 delete ${enviroment}
      #     pm2 start -n \"${environment}"\ index.js -- ${port}

  deploy-dev:
    name: deploy dev
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          port: 2345
          enviroment: 'dev'
      # - name: ... deploy success ...
      #   run: echo Start to deploy to dev ..

  tests-dev:
    name: tests dev
    runs-on: ubuntu-latest
    needs: [deploy-dev]

    steps:
      - name: ... tests success ...
        run: echo Start to test to dev ..
  

  deploy-stg:
    name: deploy stg
    runs-on: ubuntu-latest
    needs: [tests-dev]

    steps:
      - name: ... deploy success ...
        run: echo Start to deploy to stg ..

  tests-stg:
    name: tests stg
    runs-on: ubuntu-latest
    needs: [deploy-stg]

    steps:
      - name: ... tests success ...
        run: echo Start to test to stg ..
  

  deploy-prd:
    name: deploy prd
    runs-on: ubuntu-latest
    needs: [tests-stg]

    steps:
      - name: ... deploy success ...
        run: echo Start to deploy to prd ..

  tests-prd:
    name: tests prd
    runs-on: ubuntu-latest
    needs: [deploy-prd]

    steps:
      - name: ... tests success ...
        run: echo Start to test to prd ..
  

